spring.application.name=netty-test

robot.netty.enabled=true
robot.netty.port=29001
robot.netty.boss-count=1
robot.netty.worker-count=10
robot.netty.so-backlog=1024
robot.netty.keep-alive=true
robot.netty.idle-seconds=60
robot.netty.write-buffer-low-watermark=32768
robot.netty.write-buffer-high-watermark=131072

robot.protocol.max-payload-length=65536

robot.persistence.queue-capacity=10000
robot.persistence.high-watermark=8000
robot.persistence.low-watermark=4000
robot.persistence.batch-size=200
robot.persistence.flush-interval-ms=100

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/netty?&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=admin

spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
